### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by Aleadinglight** [Aleadinglight/Express-demo#2]
https://github.com/Aleadinglight/Express-demo/blob/53dde53d4afbd357964a0c0e250e61ba7fd4310f/index.js#L30-L36

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (D:\express-demo\node_modules\express\lib\response.js:767:10)
    at ServerResponse.json (D:\express-demo\node_modules\express\lib\response.js:264:10)
    at ServerResponse.send (D:\express-demo\node_modules\express\lib\response.js:158:21)
    at app.get (D:\express-demo\index.js:35:6)
    at Layer.handle [as handle_request] (D:\express-demo\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\express-demo\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\express-demo\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\express-demo\node_modules\express\lib\router\layer.js:95:5)

**Comment by Aleadinglight** [comment]
Fixed
